# Using  bullseye instead of alpine because debugger didnt work in alpine
FROM golang:1.19-bullseye

WORKDIR /app 

# Install air for hot reload
RUN go install github.com/cosmtrek/air@latest

# Install delve for debugging
RUN go install github.com/go-delve/delve/cmd/dlv@latest

COPY go.mod go.sum ./

RUN go mod download

COPY . .

CMD ["air", "-c", ".air.toml"]
