# Pin specific version for stability
# Use alpine for reduced image size
FROM node:19.4-alpine

# Specify working directory other than /
WORKDIR /usr/src/app

# Copy only files required to install
# dependencies (better layer caching)
COPY package*.json ./

RUN npm install

# Copy remaining source code AFTER installing dependencies. 
# Again, copy only the necessary files
COPY ./src/ .

CMD [ "node", "index.js" ]